rails_todos/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: "home#index"
  resources :todos do
    resources :todo_comments, only: [:new, :create]

    # collection do
    #   get'/search', to: 'todos#search'
    #   get'/visible', to: 'todos#visible'
    #   get'/hidden', to: 'todos#hidden'
    #   post '/mark_as_read', to: 'todos#mark_as_read'
    # end
    #
    # member do
    #   get 'mark_as_complete', to: 'todos#mark_as_complete'
    #   get '/hide', to: 'todos#hide'
    #   get '/share', to: 'todos#share'
    # end

  end

 # resources :todo_comments
end

rails_todos/app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { minimum: 4 }
  validates :priority, inclusion: { in: ['H','M','L'], message: "Please select a valid priority"}
  has_many :todo_comments, dependent: :destroy
end

rails_todos/app/models/todo_comment.rb
class TodoComment < ApplicationRecord
  belongs_to :todo
end

rails_todos/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

rails_todos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end 
end

rails_todos/app/controllers/todo_comments_controller.rb
class TodoCommentsController < ApplicationController

  def new
    @todo = Todo.find(params[:todo_id])
    @todo_comment = TodoComment.new
  end

  def create
  todo = Todo.find(params[:todo_id])
  todo.todo_comments.create(todo_comment_params)
  redirect_to todos_path
  end
private
  def todo_comment_params
    params.require(:todo_comment).permit(:content)
  end
end

rails_todos/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end
  def show
    @todo = Todo.find(params[:id])
  end
  def create
    @todo = Todo.create(todo_params)
    if @todo.valid?
      flash[:success] = "Your todo has been created"
      redirect_to todos_path
    else
      flash[:error] = 'Invalid'
      render :new
    end
  end
  def edit
    @todo = Todo.find(params[:id])
  end
  def update
    todo = Todo.find(params[:id])
    todo.update(todo_params)
    redirect_to todos_path
  end
  def destroy
    Todo.destroy(params[:id])
    render json: {status: 'success', message: 'todo was successfully deleted'}
  end

  private ##strong parameters
  # returns {name: 'userinput', description: 'userinput'}
  def todo_params
    params.require(:todo).permit(:name, :description, :priority)
  end

end

rails_todos/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

rails_todos/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

rails_todos/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

rails_todos/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    todos_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

rails_todos/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

rails_todos/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

rails_todos/app/helpers/application_helper.rb
module ApplicationHelper

  def custom_bootstrap_flash
  flash_messages = []
  flash.each do |type, message|
    type = 'success' if type == 'notice'
    type = 'error'   if type == 'alert'
    text = "<script>toastr.#{type}('#{message}');</script>"
    flash_messages << text.html_safe if message
  end
  flash_messages.join("\n").html_safe
end

end

rails_todos/app/helpers/home_helper.rb
module HomeHelper
end

rails_todos/app/helpers/todo_comments_helper.rb
module TodoCommentsHelper
end

rails_todos/app/helpers/todos_helper.rb
module TodosHelper
end

rails_todos/app/views/home/index.html.erb
<h1> This is my Home Page </h1>
<%= link_to 'Sign Up', new_user_registration_path %>
<%= link_to 'Log In', new_user_session_path %>
<%= link_to 'Log Out', destroy_user_session_path, method: 'DELETE' %> 

rails_todos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
    <% custom_bootstrap_flash %>
  </body>
</html>

rails_todos/app/views/todo_comments/new.html.erb
<h1> Create new todo comment </h1>
<%= form_for [@todo, @todo_comment] do |f| %>
  <%= f.label :content, 'Add your comment here!'%>
  <%=  f.text_area :content %>
  <%= f.submit%>
<% end %>

rails_todos/app/views/todos/_form.html.erb
<% @todo.errors.any? %>
<div>
  <% @todo.errors.full_messages.each do |error| %>
  <%= error %>
  <% end %>
</div>


<%= form_for @todo do |f| %>
 <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
 </div>

 <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
 </div>


 <div>
    <%= f.label :priority %>
    <%= f.select :priority, options_for_select([['High Priority', 'H'], ['Medium Priority', 'M'], ['Low Priority', 'L']]) %>
 </div>

 <div>
  <%= f.submit %>
 </div>
<% end %>

rails_todos/app/views/todos/edit.html.erb
<h2>Edit Todo</h2>
<%= render 'form' %>

rails_todos/app/views/todos/index.html.erb
<h2>Welcome to your Rails Todo List </h2>
<h4> <%= link_to 'Create a new todo', new_todo_path %>
</h4>


<% @todos.each do |todo| %>
<div class="single-todo">
  <div>
    Name <%= todo.name  %>
  </div>
  <div>
    Description: <%= todo.description  %>
  </div>

  <div>
  Comments:
  <% todo.todo_comments.each do |comment|  %>
      <%= comment.content %>
      <% end %>
  </div>

  <div>


    <%= link_to 'View', todo_path(todo), 'data-disable-with': 'Processing...' %>
    <%= link_to 'Edit', edit_todo_path(todo) %>
    <%= link_to 'Add Comment', new_todo_todo_comment_path(todo) %>
    <%= link_to 'Delete', todo_path(todo), class:'delete-todo' %>


  </div>

</div>

<% end %>

rails_todos/app/views/todos/new.html.erb
<h3>Create a new Todo</h3>
<%= render 'form' %>

rails_todos/app/views/todos/show.html.erb
<h3>Todo Details</h3>
<div>
   Name: <%=@todo.name%>
</div>

<div>
   Description: <%=@todo.description%>
</div>

<div>
   Created At: <%=@todo.created_at%>
</div>

<div>
   Updated At: <%=@todo.updated_at%>
</div>

rails_todos/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>