rails_bakery/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cakes
  resources :muffins

  root to: 'home#home'

  post '/cakes/:id/toggle-status', to: 'cakes#toggle_status', as: :toggle_cake_status

  post '/muffins/:id/toggle-status', to: 'muffins#toggle_status', as: :toggle_muffin_status
end

rails_bakery/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_bakery/app/models/cake.rb
class Cake < ApplicationRecord
end

rails_bakery/app/models/muffin.rb
class Muffin < ApplicationRecord
end

rails_bakery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_bakery/app/controllers/cakes_controller.rb
class CakesController < ApplicationController

  def index
   @cakes = params[:status] == '2' ? Cake.where(status: 2) : Cake.where(status: 1)
  end

  def toggle_status
    @cake = Cake.find(params[:id])
    if @cake.status == 1
     @cake.update(status: 2)
   else
     @cake.update(status: 1)
   end
    redirect_to cakes_path
  end

  def new
   @cake = Cake.new
  end

  def edit
   @cake = Cake.find(params[:id])
  end

  def show
   @cake = Cake.find(params[:id])
  end

  def create
   Cake.create(cake_params)
   redirect_to cakes_path
  end

  def update
   cake = Cake.find(params[:id])
   cake.update(cake_params)
   redirect_to cakes_path
  end

  def destroy
   Cake.destroy(params[:id])
   redirect_to cakes_path
  end

private
 def cake_params
  params.require(:cake).permit(:name, :description, :diameter, :price, :available_until)
 end

end

rails_bakery/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @cakes = Cake.all
    @muffins = Muffin.all
  end
end

rails_bakery/app/controllers/muffins_controller.rb
class MuffinsController < ApplicationController
  def index
   @muffins = params[:status] == '2' ? Muffin.where(status: 2) : Muffin.where(status: 1)
  end

  def toggle_status
    @muffin = Muffin.find(params[:id])
    if @muffin.status == 1
      @muffin.update(status: 2)
    else
      @muffin.update(status: 1)
    end
    redirect_to muffins_path
  end
  
    def new
     @muffin = Muffin.new
    end
    def edit
     @muffin = Muffin.find(params[:id])
    end
    def show
     @muffin = Muffin.find(params[:id])
    end
    def create
     Muffin.create(muffin_params)
     redirect_to muffins_path
    end
    def update
     muffin = Muffin.find(params[:id])
     muffin.update(muffin_params)
     redirect_to muffins_path
    end
   def destroy
    Muffin.destroy(params[:id])
    redirect_to muffins_path
    end
  private
   def muffin_params
    params.require(:muffin).permit(:name, :description, :category, :price, :available_until)
   end

end

rails_bakery/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_bakery/app/helpers/cakes_helper.rb
module CakesHelper
end

rails_bakery/app/helpers/muffins_helper.rb
module MuffinsHelper
end

rails_bakery/app/views/cakes/_form.html.erb
<%= form_for @cake do |c| %>
 <div>
    <%= c.label :name %>
    <%= c.text_field :name %>
 </div>

 <div>
    <%= c.label :description %>
    <%= c.text_field :description %>
 </div>


  <div>
     <%= c.label :diameter %>
     <%= c.number_field :diameter %>
  </div>

  <div>
     <%= c.label :price %>
     <%= c.number_field :price %>
  </div>

  <div>
     <%= c.label :available_until %>
     <%= c.date_field :available_until %>
  </div>


 <div>
  <%= c.submit %>
 </div>

<% end %>

rails_bakery/app/views/cakes/edit.html.erb
<h2>Edit Your Cake</h2>
<%= render 'form' %>

rails_bakery/app/views/cakes/index.html.erb
<h2>Welcome to the Cakes Area! </h2>
<h4> <a href="<%= new_cake_path %>"> Create a Cake  </a></h4>

<h5><a href="/cakes?status=2">View Hidden</a></h5>



<% @cakes.each do |cake| %>
<div>
  Name <%= cake.name  %>
</div>
<div>
  Description: <%= cake.description  %>
</div>

<div>
  Diameter: <%= cake.diameter  %>
</div>

<div>
  Price: <%= cake.price  %>
</div>

<div>
  Available Until: <%= cake.available_until  %>
</div>
<div>

  <a href="<%=toggle_cake_status_path(cake)%>" data-method="POST" data-disable-with=“Hiding..”> Hide</a>

  <a href="<%=cake_path(cake)%>" data-disable-with=“Processing…”> View Details</a>

  <a href="<%=edit_cake_path(cake)%>"> Edit </a>

  <a href="<%=cake_path(cake)%>" data-method="DELETE"> Delete </a>


</div>

<% end %>

rails_bakery/app/views/cakes/new.html.erb
<h4>Create a new Cake!</h4>
<%= render 'form' %>

rails_bakery/app/views/cakes/show.html.erb
<h3>Cake Details</h3>
<div>
   Name: <%=@cake.name%>
</div>

<div>
   Description: <%=@cake.description%>
</div>

<div>
   Diameter: <%=@cake.diameter%>
</div>

<div>
   Price: <%=@cake.price%>
</div>

<div>
   Available Until: <%=@cake.available_until%>
</div>

<div>
   Created At: <%=@cake.created_at%>
</div>

<div>
   Updated At: <%=@cake.updated_at%>
</div>

rails_bakery/app/views/home/home.html.erb
<h2>Welcome to the Bakery</h2>
<h4>Here are our top cakes!</h4>
<h5> <a href="<%=cakes_path%>"> See All Cakes </a>

<% @cakes.last(3).each do |cake| %>
<div>
  Name <%= cake.name  %>
</div>
<div>
  Description: <%= cake.description  %>
</div>

<div>
  Diameter: <%= cake.diameter  %>
</div>

<div>
  Price: <%= cake.price  %>
</div>
<% end %>
<br>
<br>
<h4>Here are our top muffins</h4>
<h5> <a href="<%=muffins_path%>"> See All Muffins</a>
<% @muffins.last(3).each do |muffin| %>
<div>
  Name <%= muffin.name  %>
</div>
<div>
  Description: <%= muffin.description  %>
</div>

<div>
  Diameter: <%= muffin.category  %>
</div>

<div>
  Price: <%= muffin.price  %>
</div>

<% end %>

rails_bakery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBakery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_bakery/app/views/muffins/_form.html.erb
<%= form_for @muffin do |m| %>
 <div>
    <%= m.label :name %>
    <%= m.text_field :name %>
 </div>

 <div>
    <%= m.label :description %>
    <%= m.text_field :description %>
 </div>


  <div>
     <%= m.label :category %>
     <%= m.text_field :category %>
  </div>

  <div>
     <%= m.label :price %>
     <%= m.number_field :price %>
  </div>

  <div>
     <%= m.label :available_until %>
     <%= m.date_field :available_until %>
  </div>

 <div>
  <%= m.submit %>
 </div>

<% end %>

rails_bakery/app/views/muffins/edit.html.erb
<h2>Edit Your Cake</h2>
<%= render 'form' %>

rails_bakery/app/views/muffins/index.html.erb
<h2>Welcome to the muffin </h2>
<h4> <a href="<%= new_muffin_path %>"> Create a Muffin  </a></h4>

<h5><a href="/muffins?status=2">View Hidden</a></h5>

<% @muffins.each do |muffin| %>
<div>
  Name <%= muffin.name  %>
</div>
<div>
  Description: <%= muffin.description  %>
</div>

<div>
  Category: <%= muffin.category  %>
</div>

<div>
  Price: <%= muffin.price  %>
</div>

<div>
  Available Until: <%= muffin.available_until  %>
</div>
<div>

  <a href="<%=toggle_muffin_status_path(muffin)%>" data-method="POST" data-disable-with=“Hiding..”> Hide</a>

  <a href="<%=muffin_path(muffin)%>" data-disable-with=“Processing…”> View Details</a>

  <a href="<%=edit_muffin_path(muffin)%>"> Edit </a>

  <a href="<%=muffin_path(muffin)%>" data-method="DELETE"> Delete </a>


</div>

<% end %>

rails_bakery/app/views/muffins/new.html.erb
<h4>Create a new Muffin!</h4>
<%= render 'form' %>

rails_bakery/app/views/muffins/show.html.erb
<h3>Muffin Details</h3>
<div>
   Name: <%=@muffin.name%>
</div>

<div>
   Description: <%=@muffin.description%>
</div>

<div>
   Category: <%=@muffin.category%>
</div>

<div>
   Price: <%=@muffin.price%>
</div>

<div>
   Available Until: <%=@muffin.available_until%>
</div>

<div>
   Created At: <%=@muffin.created_at%>
</div>

<div>
   Updated At: <%=@muffin.updated_at%>
</div>